### PR TITLE
Fix ci

### PR DESCRIPTION
**Pull request by anpin**
https://github.com/tweag/jupyenv/pull/562

### CODE REVIEW

**Comment by anpin** [comment]
@GTrunSec I was hoping that would trigger build, but it didn’t.

**Comment by anpin** [comment]
still hangs. locally runs fine.

**Comment by anpin** [comment]
removed kernel tests from flake check

**Comment by anpin** [comment]
I'm puzzled. Seems like every minimal kernel installed via poetry is broken. Those defined via custom kernelFunc are working fine. 

I can reproduce this behavior locally.

**Comment by anpin** [comment]
Scala kernel seems to be not compatible with current scala version. Elm, Julia, Haskel and Postgres I’m unable to compile at the moment.

**Comment by GTrunSec** [comment]
@anpin thanks for your helping, I think we can just fix the Haskell part and website would be enough.  I'm going to rewrite jupyenv https://github.com/GTrunSec/jupyenv-next, there is no reason to spend time on the bump up to the latest locks.

**Comment by anpin** [comment]
I managed to fix missing deps for haskell, but it is still failing with some cryptic error
```console
└[~/projects/jupyenv]> nix build .\#jupyterlab-kernel-example-haskell-minimal -L --show-trace
warning: Git tree '/home/a/projects/jupyenv' is dirty
ihaskell-with-packages-ghc910> created 3 symlinks in user environment
ihaskell-with-packages-ghc910> mv: cannot move '/nix/store/pfyja4zf6sjfwiv4ws1r7aapsa07fs6d-ihaskell-with-packages-ghc910/bin/HsColour' to '/nix/store/pfyja4zf6sjfwiv4ws1r7aapsa07fs6d-ihaskell-with-packages-ghc910/bin/.HsColour-wrapped': Permission denied
error: builder for '/nix/store/9i1mry02020c3gabz8dx8mm7dlfw16x2-ihaskell-with-packages-ghc910.drv' failed with exit code 1;
       last 2 log lines:
       > created 3 symlinks in user environment
       > mv: cannot move '/nix/store/pfyja4zf6sjfwiv4ws1r7aapsa07fs6d-ihaskell-with-packages-ghc910/bin/HsColour' to '/nix/store/pfyja4zf6sjfwiv4ws1r7aapsa07fs6d-ihaskell-with-packages-ghc910/bin/.HsColour-wrapped': Permission denied
       For full logs, run 'nix log /nix/store/9i1mry02020c3gabz8dx8mm7dlfw16x2-ihaskell-with-packages-ghc910.drv'.
error: 1 dependencies of derivation '/nix/store/cj20wqaiqi87izhc5g3scxgldjgnjpzn-wrapper-chmod-python3-3.12.7-env.drv' failed to build
```
which seems like an upstream issue https://github.com/IHaskell/IHaskell/issues/1434

**Comment by anpin** [comment]
@GTrunSec what is the rationale behind full rewrite? Are you planning to merge it in this repo or it will be separate project?

**Comment by anpin** [comment]
last commit allows the haskell kernel to compile, however tests are failing due to missing kernels / kernel.json file

**Comment by anpin** [comment]
I forked the ${ihaskell}/nix/release.nix to customize kernel.json generation. The kernel starts, but fails instantly with 
```console
> result/bin/python examples/haskell/minimal/test.py
/nix/store/cv8zpwnabrnggb1lxfjy6hksvfl6hfdr-python3-3.12.7-env/lib/python3.12/site-packages/IPython/paths.py:69: UserWarning: IPython parent '/' is not a writable location, using a temp directory.
  warn("IPython parent '{0}' is not a writable location,"
ihaskell:
Ran commands:
ghc-pkg check
which ghc-pkg

Exception: user error (shelly did not find ghc-pkg in the PATH: /nix/store/z0ivg3dbal4sk5h0c7p1pfkxc7ff98ri-nodejs-20.18.0/bin:/run/wrappers/bin:/home/a/.nix-profile/bin:/nix/profile/bin:/home/a/.local/state/nix/profile/bin:/etc/profiles/per-user/a/bin:/nix/var/nix/profiles/default/bin:/run/current-system/sw/bin:/home/a/.zsh/plugins/zsh-syntax-highlighting:/home/a/.zsh/plugins/zsh-autosuggestions:/home/a/.zsh/plugins/zsh-dotnet-completion)
HasCallStack backtrace:
  finally, called at compiler/GHC/Utils/Panic.hs:303:7 in ghc-9.10.1-inplace:GHC.Utils.Panic


Traceback (most recent call last):
  File "/home/a/projects/jupyenv/examples/haskell/minimal/test.py", line 14, in <module>
    test_nb()
  File "/nix/store/cv8zpwnabrnggb1lxfjy6hksvfl6hfdr-python3-3.12.7-env/lib/python3.12/site-packages/testbook/testbook.py", line 61, in wrapper
    with self.client.setup_kernel():
         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/px2nj16i5gc3d4mnw5l1nclfdxhry61p-python3-3.12.7/lib/python3.12/contextlib.py", line 137, in __enter__
    return next(self.gen)
           ^^^^^^^^^^^^^^
  File "/nix/store/cv8zpwnabrnggb1lxfjy6hksvfl6hfdr-python3-3.12.7-env/lib/python3.12/site-packages/nbclient/client.py", line 603, in setup_kernel
    self.start_new_kernel_client()
  File "/nix/store/cv8zpwnabrnggb1lxfjy6hksvfl6hfdr-python3-3.12.7-env/lib/python3.12/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/px2nj16i5gc3d4mnw5l1nclfdxhry61p-python3-3.12.7/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/nix/store/cv8zpwnabrnggb1lxfjy6hksvfl6hfdr-python3-3.12.7-env/lib/python3.12/site-packages/nbclient/client.py", line 566, in async_start_new_kernel_client
    await ensure_async(self.kc.wait_for_ready(timeout=self.startup_timeout))
  File "/nix/store/cv8zpwnabrnggb1lxfjy6hksvfl6hfdr-python3-3.12.7-env/lib/python3.12/site-packages/jupyter_core/utils/__init__.py", line 198, in ensure_async
    result = await obj
             ^^^^^^^^^
  File "/nix/store/cv8zpwnabrnggb1lxfjy6hksvfl6hfdr-python3-3.12.7-env/lib/python3.12/site-packages/jupyter_client/client.py", line 203, in _async_wait_for_ready
    raise RuntimeError(msg)
RuntimeError: Kernel died before replying to kernel_info
```

At this point I'm out of ideas and time I can spend on this.

**Comment by anpin** [comment]
well that's rather peculiar: this last commit runs ihaskell fine in CI, but locally it has the error posted above

**Comment by GTrunSec** [comment]
@anpin Could you try the change the julia to the `nixpkgs_stable.julia`? I think the julia-1.9.3 would be ok for passing the building.

**Comment by anpin** [comment]
I will try, but somehow current version worked on my nixos machine

**Comment by GTrunSec** [comment]
> I will try, but somehow current version worked on my nixos machine

if the current version works well, you can just revert the comment to  `precompile = false;` in the example/julia.nix.

**Comment by anpin** [comment]
both `precompile = false`, `precompile = true` and commented version make no difference in my case, build succeeds regardless of any change

**Comment by GTrunSec** [comment]
> both `precompile = false`, `precompile = true` and commented version make no difference in my case, build succeeds regardless of any change

Yeh, I knew it, just for passing the CI

**Comment by anpin** [comment]
@GTrunSec it is finally green

**Comment by GTrunSec** [comment]
@anpin thanks, good job

**Review by GTrunSec — APPROVED** [review]
LGTM

**Pull request merged**
