### PR TITLE
Refactor: cleanup the code base v2

### PR DESCRIPTION
**Pull request by GTrunSec**
Fixes: https://github.com/tweag/jupyenv/issues/447

### CODE REVIEW

**Comment by GTrunSec** [comment]
pretty weird.

I can not import such as https://github.com/ibis-project/ibis/blob/master/nix/ibis.nix#L23 overlays from the evalModule. Unless those overlays are imported from poetry.module.

```
error: infinite recursion encountered

       at /nix/store/yf26s7734ql7q05zlq6nq4y5q3rjyhj7-source/pkgs/top-level/python-packages.nix:9:19:

            8|
            9| self: super: with self; {
             |                   ^
           10|
(use '--show-trace' to show detailed location information)
```

**Review by garbas — COMMENTED** [review]
I don't think this cleanup is needed since @djacu is working on getting rid of `default.nix` stuff to finish the transition to the modules. But it is step in the right direction.

I'd let @djacu make a judgement on this since this will probably conflict with his work (in case he already started it)

**Comment by GTrunSec** [comment]
I think the current cleanup is necessary, why? 

1. There is a case of arguments overuse
2. and some configurations are a bit complicated
3. we need a lightweight interface to config our kernel.
4. fully mitigate to nixosModules

**Comment by garbas** [comment]
> I think the current cleanup is necessary, why?
> 
>     1. There is a case of arguments overuse (so hard to debug that)
> 
>     2. and some configurations are a bit complicated
> 
>     3. we need a lightweight interface to config our kernel.
> 
>     4. fully mitigate to nixosModules

Oh don't get me wrong I agree with all of your changes here. I was pointing out that this might conflict with the work @djacu is working on as well.

**Comment by GTrunSec** [comment]
> Oh don't get me wrong I agree with all of your changes here
I see, sorry about that.

> I was pointing out that this might conflict ..

it doesn’t matter. If @djacu could provide a better solution.

**Comment by djacu** [comment]
Hey @GTrunSec 

Thanks for the PR and effort. We are going to go a different path.
We already moved the kernel modules and kernel examples to their final location. Now I am working to get rid of the bloat and extra functions that add unneeded complexity.

**Pull request closed without merging**
