### PR TITLE
ARM macOS support

### LINKED ISSUE #388: [Bug]: Missing aarch64-darwin attributes (support for MacOS M1)
### Current Behavior

First of all, thank you for the package!

I'm still learning about it, but I use `nix-darwin` and `home-manager` in an M1 MackBook Pro. 

I followed the [installation instructions](https://jupyterwith.tweag.io/getting-started/) and got this error:

```
error: flake 'jupyterWith' does not provide attribute 'apps.aarch64-darwin.default', 'defaultApp.aarch64-darwin', 'packages.aarch64-darwin.default' or 'defaultPackage.aarch64-darwin'
```
Is it because aarch64-darwin is not supported? Will it ever be?

### Expected Behavior

The notebook runs.

### Steps To Reproduce

Follow the [installation instructions](https://jupyterwith.tweag.io/getting-started/).

### OS

```shell
- system: `"aarch64-darwin"`
 - host os: `Darwin 22.1.0, macOS 13.0.1`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.11.1`
 - channels(root): `"nixpkgs"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`
```

### Version

Can't tell

### Additional Context

_No response_

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by wokalski**
Fixes #388 

I was able to run jupyterlab successfully after this change. Let me know if I'm missing anything!

### CODE REVIEW

**Comment by srid** [comment]
Also need to modify the template,

https://github.com/tweag/jupyenv/blob/3ad2c9512c9efd586cf63adde454e734a8ce049c/template/flake.nix#L25-L28

I observe that this project has no CI for macOS? How will macOS support be tested in CI going forward?

**Comment by richban** [comment]
```
➜ nix run
warning: Git tree '/Users/richard.banyi/Developer/nix-project-flakes' is dirty
error: attribute 'aarch64-darwin' missing

       at /nix/store/nvss7vjwjdq6prxfwf24swzksn4f6cvm-source/jupyenv/flake.nix:32:18:

           31|       system: let
           32|         inherit (jupyenv.lib.${system}) mkJupyterlabNew;
             |                  ^
           33|         jupyterlab = mkJupyterlabNew ({...}: {
(use '--show-trace' to show detailed location information)
```

**Comment by srid** [comment]
Ping.

Can we get this PR merged?

**Comment by GTrunSec** [comment]
Could you re-submit the commits to adding these systems? @wokalski 
```
  systems = [
        "x86_64-linux"
        "x86_64-darwin"
        "aarch64-linux"
        "aarch64-darwin"
      ];
```

**Comment by wokalski** [comment]
Sorry. I ended up not using it so i dont have interest working on this.

**Comment by GTrunSec** [comment]
it's ok, im going to refactor the jupyenv on this weekend.

**Pull request closed without merging**
